### ISSUE TITLE
[AT] As a QA engineer, I want to setup the Environment for automation.

### ISSUE THREAD

**Issue by Mangesh-Shirodkar** [pioneer-pay/pioneer-pay-web-app-automation#1]
Setup for the automation testing environment using Selenium, Java and respective dependencies in the project

**Acceptance Criteria**

- Project having POM design pattern.
- All the dependencies included in POM.xml file
- Web drivers are included in project

**Comment by blazelon** [comment]
Merge branch `1-at-env-setup` with `develop` and then close the issue.

**Comment by Mangesh-Shirodkar** [comment]
Branch 1-at-env-setup is merged with develop.
